POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Mark",
    "email": "mark@email.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "3f7efa38-6c14-409c-a032-7ffbca7f7132"
}


###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "80ce7aa5-378a-456c-b4e7-41f18fa718ea"
}

###


POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "a02f8afc-8446-4ca9-9dbe-829c10b8a23d",
    "account_id_to": "2473ec29-ca0e-46ef-8f1e-416e7d66844c",
    "amount": 1
    
}

###


POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "2473ec29-ca0e-46ef-8f1e-416e7d66844c",
    "account_id_to": "a02f8afc-8446-4ca9-9dbe-829c10b8a23d",
    "amount": 1
    
}